accent = "#B3E6DB"
cursor = "#B3E6DB"
foreground = "#F8F9E8"
background = "#232A2E"
selection_foreground = "#F8F9E8"
selection_background = "#839E9A"

color0 = "#455355"
color1 = "#F57F82"
color2 = "#CBE3B3"
color3 = "#B3E6DB"
color4 = "#B2CAED"
color5 = "#B3E6DB"
color6 = "#2B3034"
color7 = "#ADC9BC"
color8 = "#576869"
color9 = "#F57F82"
color10 = "#B2CAED"
color11 = "#F5D098"
color12 = "#B2CAED"
color13 = "#F5D098"
color14 = "#B2CAED"
color15 = "#839E9A"
